### ISSUE TITLE
Error en la ubicación

### ISSUE THREAD

**Issue by Alvax10** [facuariasla/lost-pets-server#1]
Buenas facu, como va? Felicidades por el desafío, esta TREMENDO!
A pesar de eso, hay un pequeño error a la hora de editar la mascota, te lo dejo a continuación:

A la hora de editar la ubicación de la mascota, en la page "mis mascotas reportadas" cambia, pero en la "home" no, adjunto fotos:

![Screenshot from 2022-06-26 14-51-02](https://user-images.githubusercontent.com/64299010/175827421-dc14f4d8-5ef1-4ff4-bb24-fc7aeec28b50.png)
![Screenshot from 2022-06-26 14-51-18](https://user-images.githubusercontent.com/64299010/175827424-cc2f1606-16b1-458e-a626-1c3321784d88.png)

Avisame por acá cuando lo hayas arreglado así lo vuelvo a chequear y lo vuelvo a revisar. Otra cosita más, estaría bueno que cuando voy a "mi perfil" me deje editar algunos datos de mi cuenta, adjunto foto de como se ve:

![Screenshot from 2022-06-26 14-54-17](https://user-images.githubusercontent.com/64299010/175827501-d9a140c5-4e9d-4f9b-bef0-30c77430716c.png)
Estaría bueno al menos cambiar el  nombre o la contraseña, excluyendo esto el desafío está tremendo!. Aguardo una respuesta.

Saludos y suerte!

**Comment by facuariasla** [comment]
Gracias Alvax! Daale excelente, cuando pueda le pego una miradita y corrijo todo eso

**Comment by Alvax10** [comment]
Buenas facu, fijate que lo de la ubicación todavía no funciona no se si ya le hechaste una miradita o no, te adjunto fotos:

Primero había puesto la ubicación en neuquen (ubicación random), luego puse la ubicación en mi ciudad y en mi barrio pero todavía me marca que no tengo ninguna mascota cerca:
![Screenshot from 2022-06-27 12-49-55](https://user-images.githubusercontent.com/64299010/175981459-8b8ffc84-8389-4db0-acf7-908d8fa3e11e.png)

![Screenshot from 2022-06-27 12-50-03](https://user-images.githubusercontent.com/64299010/175981478-154ad198-4fde-43c2-998b-2e76c86f6af4.png)

Y lo del perfil, estaría bueno que haya un botón para que actualice mi info si quiero cambiarla (ej: cambiar mi nombre):
![Screenshot from 2022-06-27 12-46-32](https://user-images.githubusercontent.com/64299010/175981749-258f09a0-6d9b-4fa3-bc0d-b105a782aa98.png)

![Screenshot from 2022-06-27 12-46-44](https://user-images.githubusercontent.com/64299010/175981755-77662f4a-6337-4b47-923a-d93a76a676d5.png)

Vamos que ya estás a nada de terminar! 💪🏻  cualquier cosita nos vemos en discord! Saludoss

**Comment by facuariasla** [comment]
Sii, estoy tocando el back, lo del actualizar perfil por ahora jaja con cambios de datos en el Auth y todo eso.
Y con respecto al la ubicación, lo acabo de ver y si es verdad, no cambia la latitud ni longitud (el nombre de la ubicación si) y es porque tengo a Mapbox en un componente distinto, y le tengo que hacer pasar las props al formulario y viceversa, asi que eso seguro me lleva un tiempo más, cuando lo tenga todo listo lo vuelvo a enviar, gracias Alvax!

**Comment by facuariasla** [comment]
Alvaa, teóricamente YA ESTARÍA si se rompe me mato jaja un saludo

**Comment by Alvax10** [comment]
Genial facu! Ahora le pego una ojeada
