### ISSUE TITLE
No modifica la data

### ISSUE THREAD

**Issue by Alvax10** [facuariasla/lost-pets-server#2]
Buenas facu, ahí probando ahora si me aparece la mascota en la página principal!
![Screenshot from 2022-06-28 10-06-44](https://user-images.githubusercontent.com/64299010/176186816-95644688-63b7-4979-871d-4eeda63ea8ff.png)

Lo malo es que no me deja actualizar ni el nombre ni el email :(
![Screenshot from 2022-06-28 10-04-51](https://user-images.githubusercontent.com/64299010/176186699-1e938cc7-504e-4719-8090-4ed87dd70b2e.png)

Y con mi contra me pone que la antigua no es la correcta, probé miles de contras que pude haber puesto y no me toma ninguna asique acá pueden estar pasando 2 cosas:

1- Soy un boludo que no se acuerda la contraseña
2- Está tomando la contra nueva como la vieja

Ahora voy a hacerme otra cuenta para confirmar si soy yo xd, adjunto foto:

![Screenshot from 2022-06-28 10-06-38](https://user-images.githubusercontent.com/64299010/176187199-ecf72878-6cb8-46d6-a0d4-4d3d6da7f2d4.png)

**Comment by Alvax10** [comment]
Recién cree una cuenta nueva, fui a modificar la contraseña y me volvió a tirar lo mismo:
![Screenshot from 2022-06-28 10-14-07](https://user-images.githubusercontent.com/64299010/176187745-09abac21-9d6b-452b-8024-eef27ef5f7ce.png)

Asique vas a tener que corregir ambas cosas, acordate que estamos en discord por cualquier cosa que te esté costando resolver!

**Comment by facuariasla** [comment]
Acabo de ver, y era que al crear un user guardaba mal un dato en el localStorage no lo puedo creer, ni se como me di cuenta, pero bueno fijate si está todo ahi. Era un efecto dominó que afectaba a una banda de peticiones xd

**Comment by Alvax10** [comment]
Genial que te hayas dado cuenta! Y mas si ese error estaba complicado, en
un ratito me vuelvo a fijar!🙌

**Comment by Alvax10** [comment]
Facu, ahora me tira estos errores:

![Screenshot from 2022-06-28 12-54-21](https://user-images.githubusercontent.com/64299010/176225430-9b10caa8-4d12-431e-a467-83535b070058.png)

![Screenshot from 2022-06-28 12-53-18](https://user-images.githubusercontent.com/64299010/176226664-22bae97e-2c39-4886-9abe-9aa5f0199af2.png)

**Comment by facuariasla** [comment]
jaja no le puse el template string al mensaje.
Se ve que ahi te quedo el valor del user en otra parte del localStorage (que tenia mal), y ahora que ya estas logeado, no la toma.
Ahi te borro tus users manualmente, y si cerras sesion en tu navegador, y te volveas a crear etc. DEBERIA funcionar, igual tranqui, avisame si te anda, yo ya lo estoy chequeando

**Comment by Alvax10** [comment]
Claaro, yo seguía con el usuario "mal creado", ahora me registro desde cero y te aviso! ya madaste el desafío otra vez? porque no me llegó

**Comment by Alvax10** [comment]
Ahora anda perfecto facu!! Mandate el desafío así te lo apruebo, sinceramente tremenda webapp te mandaste, se la mandé a los demás tutores y les encantó. Se nota el laburo que le pusiste a todo 10/10, nos vemos en el módulo 8 con react! 🥳

**Comment by facuariasla** [comment]
Gracias! Si me cebe un toque con react porque estuve aprendiendo y aproveché a poner un poco en práctica jaja. Mil gracias también por tomarte todo el tiempo!

**Comment by Alvax10** [comment]
Increible 👏🏻, ahí me llegó el desafío y lo aprobé facu, No hay problema! 🙌🏻
